Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/05/2025
Var
// Seção de Declarações das variáveis 
num1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Fale um número")
leia(num1)
escreval("O antecessor do seu número é", num1 - 1)

Fimalgoritmo