Algoritmo "Tipos de Repetição - AULA 6"

Var
i : inteiro

Inicio
i <- 1
// positivo , verifica e faz
//enquanto (i <= 5) faca
//     escreval("Escrevi ", i)
//     i <- i + 1
//fimEnquanto

//i<- 1
//repita
//    escreval("Escrevi", i)
//    i<- i + 1
//ate(i >= 5)
//O REPITA é o contrário do ENQUANTO
// Sempre usando o sinal contrário

//FOR = WHILE
para i <- 1 ate 20 passo 5 faca
     escreval("Escrevi", i)
fimPara


Fimalgoritmo